# Generated by Django 4.2.4 on 2024-03-13 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='signupdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suname', models.CharField(blank=True, max_length=100, null=True)),
                ('suemail', models.CharField(blank=True, max_length=100, null=True)),
                ('sunumber', models.CharField(blank=True, max_length=100, null=True)),
                ('supassword', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
