# Generated by Django 4.2.4 on 2024-03-13 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='signupdb',
            new_name='registerdbb',
        ),
    ]
